/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ApiHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DashborionApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "TokensTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}